on:
  push:
    branches:
      - main
      - master

name: Build and Release APKs

jobs:
  build:
    name: Build & Release APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean

      # Build separate APKs per ABI
      - run: flutter build apk --split-per-abi || true


      # Upload the APKs as GitHub release assets
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "This release contains the latest debug APKs for different ABIs."
